import React from "react";
import Head from "next/head";
import Navbar from "~/components/Navbar";
import ClanTable from "~/components/ClanTable";

export default function Clani() {
  return (
    <>
      <Head>
        <title>MojPGD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="flex w-full flex-col items-center justify-center">
        <div className="navbar z-50">
          <Navbar />
        </div>
      </div>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#111827] to-magenta">
        <div className="mx-auto mt-28 justify-center">
          <ClanTable />
        </div>
      </main>
    </>
  );
}
