// Home.jsx

import React from "react";
import Head from "next/head";
import Navbar from "~/components/Navbar";
import Okvir from "~/components/Okvir";
import { signIn, useSession } from "next-auth/react";
import Image from "next/image";

export default function Home() {
  const { data: sessionData } = useSession();

  if (!sessionData) {
    // If user is not logged in, show authentication form
    return (
      <div className="flex flex-col items-center justify-center h-screen bg-gradient-to-b from-[#111827] to-magenta">
        <Head>
          <title>MojPGD</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <div className="flex flex-col items-center justify-center">
          <div className="mb-32 animate-float">
            <Image src="/logo.png" alt="Logo" width={350} height={350} />
          </div>
          <button
            onClick={() => signIn()}
            className="mt-16 bg-red-600 hover:bg-red-700 text-white font-bold py-6 px-16 rounded-full transform transition duration-300 ease-in-out hover:-translate-y-1 hover:scale-110 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 shadow-2xl text-2xl"
            style={{ boxShadow: "0px 10px 15px rgba(0, 0, 0, 0.6)" }}
          >
            Prijava
          </button>
        </div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>MojPGD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="flex flex-col items-center justify-center bg-gradient-to-b from-[#111827] to-magenta pt-24">
        <div className="navbar z-50">
          <Navbar />
        </div>
        <div className="flex w-full flex-col items-center justify-center">
          <div className="mt-16 grid grid-cols-3 gap-8 overflow-y-scroll px-8 pb-8">
            <Okvir />
            <Okvir />
            <Okvir />
            <Okvir />
            <Okvir />
            <Okvir />
          </div>
        </div>
      </main>
    </>
  );
}
