import React from "react";
import Head from "next/head";
import Navbar from "~/components/Navbar";
import ClanTable from "~/components/ClanTable";
import { signIn, useSession } from "next-auth/react";
import Image from "next/image";


export default function Clani() {
  const { data: sessionData } = useSession();

  if (!sessionData) {
    return (
      <div className="flex h-screen flex-col items-center justify-center bg-gradient-to-b from-[#111827] to-magenta">
        <Head>
          <title>MojPGD</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <div className="flex flex-col items-center justify-center">
          <div className="animate-float mb-48">
            <Image src="/logo.png" alt="Logo" width={320} height={320} />
          </div>
          <button
            onClick={() => signIn()}
            className="btn w-40 h-12"
          >
            Prijava
          </button>
        </div>
      </div>
    );
    return null;
  }


  return (
    <>
      <Head>
        <title>MojPGD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="flex w-full flex-col items-center justify-center">
        <div className="navbar z-50">
          <Navbar />
        </div>
      </div>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#111827] to-magenta">
        <div className="mx-auto mt-28 justify-center">
          <ClanTable />
        </div>
      </main>
    </>
  );
}
