import React, { useState, useEffect } from "react";
import Head from "next/head";
import Navbar from "~/components/Navbar";
import { api } from "~/utils/api";
import { useSession } from "next-auth/react"; // Ensure correct import

export default function LetnoPorocilo() {
  const { data: session, status } = useSession();
  const [yearlyReport, setYearlyReport] = useState(null);
  const [dataLoaded, setDataLoaded] = useState(false);

  useEffect(() => {
    async function fetchYearlyReport() {
        try {
          const response = await api.getYearlyReport({ year: 2024 });
          console.log("API Response:", response);
          setYearlyReport(response);
          setDataLoaded(true); // Set dataLoaded to true when data is fetched
        } catch (error) {
          console.error("Error fetching yearly report:", error);
        }
      }
      
  
    fetchYearlyReport();
  }, []);

  return (
    <>
      <Head>
        <title>MojPGD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="flex w-full flex-col items-center justify-center">
        <div className="navbar">
          <Navbar />
        </div>
      </div>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#111827] to-magenta">
        {dataLoaded && yearlyReport && (
          <div>
            <h1>Yearly Report for 2024</h1>
            <p>Number of Drivings: {yearlyReport.voznje}</p>
            <p>Number of Members: {yearlyReport.člani}</p>
            <p>Yearly Expenses: {yearlyReport.izdatki} EUR</p>
            <p>Number of Interventions: {yearlyReport.intervencije}</p>
          </div>
        )}
        {!dataLoaded && (
          <p>Loading...</p>
        )}
      </main>
    </>
  );
}
