import React, { useState, useEffect } from "react";
import Head from "next/head";
import Navbar from "~/components/Navbar";
import { api } from "~/utils/api";
import { useSession } from "next-auth/react";

export default function LetnoPorocilo() {
  const [startDate, setStartDate] = useState(
    new Date("2000-01-01").toISOString().split("T")[0],
  );
  const [endDate, setEndDate] = useState(
    new Date().toISOString().split("T")[0],
  );
  const {
    data: reportData,
    error,
    refetch,
  } = api.post.getYearlyReport.useQuery({
    startDate: new Date(startDate || "2000-01-01"), // Pass startDate with a default value
    endDate: new Date(endDate || new Date()), // Pass endDate with a default value
  });

  useEffect(() => {
    // Fetch data for the selected dates when the component mounts or when startDate or endDate changes
    const fetchData = async () => {
      try {
        await refetch(); // Just call refetch without any parameters
      } catch (error) {
        // Handle errors here
        console.error("Error fetching yearly report:", error);
      }
    };

    fetchData(); // Call the fetch function
  }, [startDate, endDate, refetch]);

  return (
    <>
      <Head>
        <title>MojPGD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="flex w-full flex-col items-center justify-center">
        <div className="navbar">
          <Navbar />
        </div>
      </div>
      <main
        className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#111827] to-magenta"
        style={{ color: "#fff" }}
      >
        <div>
          <h1>Select Dates</h1>
          <label>Start Date:</label>
          <input
            type="date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
          />
          <label>End Date:</label>
          <input
            type="date"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
          />
        </div>
        {reportData && (
          <div>
            <h1>Yearly Report</h1>
            <p>Total Drivings: {reportData.voznje}</p>
            <p>Total Members: {reportData.člani}</p>
            <p>Yearly Expenses: {reportData.izdatki} €</p>
            <p>Total Interventions: {reportData.intervencije}</p>
          </div>
        )}
      </main>
    </>
  );
}
